Delete Deploy_VPWS_L3VPN_EVPN_and _Default_Routing_Instance_services.
This file causes issues with clone and prevents me from creating a PR.
```
error: invalid path 'CloudVision_Studios/WAN_Services_Studio/Deploy_VPWS_L3VPN_EVPN_and _Default_Routing_Instance_services.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```